travis:
  secure:
    BINSTAR_TOKEN: QXmNKU212T8FGObL13QG28AvKmL9MgF+/C9UtmlBxVlgz2iM5xps9U30pK6T3pzsXzp2EszmrXnF0qQK6Fo/YcQZtbSiZiSVHZZJjIeKNNwD2kCwRG6WFefGUH+8bdV1tgXhVwnrFGs2XY+Awbx8NkABfy6kyOCn+ZMTzAV5JznnfSsMoR12yp/BZIiXlhFzRdLaKGrLDZ9NfY58f4OumMw6LHE53qh/o7YCATKMKQNJTCc9ENQYYIvajlORIai0M58hngN0LOzLWzCGS9ECIDVZSa+v7YaaMEL6Vxze5iII6VAZ38xAeOtsTUchNfFYEkRNGKqeyTbWU8HaJ3ATRPYE33HzfA9pVq0SQLlfhSSdR/g5aQ5tkP6M490U3sz6+C0yYIVbq3VGHu3QmEkwO6WUF9cfzJ9AM4Vcz1v5Y+B74rlGupySt8JB9MjbzpP0XKJGCXl5vtg6wrswK5KM88npZy03Mn1aqtlbS0XWCD9CmWCmHeaOLVY7TcsQqHGjUDdeSarU45DQoiHT4Qy4CK750ypssONYQ2Z5NhzobhdU+DquiC+D0g3VJ7Hlo82DGa8KCrJYJ+d0NsE0xBwgPLwVd1QttkUB6sxVVRvNNvIgNCJq5Q6XWJlqVkZAygHh1DxWCOdmdlmKPPC6u3UtG2LTymDFcnZEEL+2jr7qOVA=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
